### ISSUE TITLE
django.template.exceptions.TemplateDoesNotExist: bootstrap4/layout/button.html

### ISSUE THREAD

**Issue by logut** [Noethys/Noethysweb#14]
Sur une nouvelle installation, lors de la visite de page /utilisateur/parametrage/organisateur/ajouter, une erreur `django.template.exceptions.TemplateDoesNotExist: bootstrap4/layout/button.html` est lancée.

Ça semble venir de la mise à jour de django-crispy-forms vers la version 2.0 :
> Since version 2.0, django-crispy-forms template packs are now in separate packages.
https://django-crispy-forms.readthedocs.io/en/latest/install.html#template-packs

Vu que dans requirements.txt, la version du paquet n'est pas précisée, c'est la dernière version qui s'est installé.

**Comment by logut** [comment]
Erreur similaire avec django-formtools, la mise à jour vers la version 2.4 empêche l'utilisation de l'assistant d'ajout d'activité :
```
INFO 2023-04-04 14:52:15,096 log]  OK: /utilisateur/parametrage/activites/assistant/sejour
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/formtools/wizard/views.py", line 244, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/venv/lib/python3.8/site-packages/formtools/wizard/views.py", line 261, in get
    self.storage.current_step = self.steps.first
  File "/venv/lib/python3.8/site-packages/formtools/wizard/views.py", line 67, in first
    return self.all[0]
  File "/venv/lib/python3.8/site-packages/formtools/wizard/views.py", line 49, in all
    return list(self._wizard.get_form_list())
  File "/venv/lib/python3.8/site-packages/formtools/wizard/views.py", line 222, in get_form_list
    condition = condition(self)
  File "/noethysweb/parametrage/views/activites_assistant.py", line 101, in Afficher_page_nbre_groupes
    cleaned_data = wizard.get_cleaned_data_for_step("groupes") or {}
  File "/venv/lib/python3.8/site-packages/formtools/wizard/views.py", line 494, in get_cleaned_data_for_step
    form_obj = self.get_form(
  File "/venv/lib/python3.8/site-packages/formtools/wizard/views.py", line 409, in get_form
    form_class = self.get_form_list()[step]
  File "/venv/lib/python3.8/site-packages/formtools/wizard/views.py", line 222, in get_form_list
    condition = condition(self)
  File "/noethysweb/parametrage/views/activites_assistant.py", line 101, in Afficher_page_nbre_groupes
    cleaned_data = wizard.get_cleaned_data_for_step("groupes") or {}
  File "/venv/lib/python3.8/site-packages/formtools/wizard/views.py", line 494, in get_cleaned_data_for_step
    form_obj = self.get_form(
  File "/venv/lib/python3.8/site-packages/formtools/wizard/views.py", line 409, in get_form
    form_class = self.get_form_list()[step]
  File "/venv/lib/python3.8/site-packages/formtools/wizard/views.py", line 222, in get_form_list
    condition = condition(self)
...
RecursionError: maximum recursion depth exceeded
```

**Comment by Noethys** [comment]
Bonjour,

Je viens de mettre à jour le requirements.
